version: '3'

services:
  sftp:
    build: 
      context: .
      args:
        - SFTP_PASSWORD=${SFTP_PASSWORD:?ERROR: SFTP_PASSWORD environment variable is required}
    ports:
      - "2222:22"
    environment:
      - SFTP_ROOT_FOLDER=/sftp/data
    volumes:
      - /Users/jmahe/sftp_data:/sftp/data
