
services:
  sftp:
    build:
      context: .
      args:
        - SFTP_PASSWORD=${SFTP_PASSWORD}
        - SFTP_USERNAME=${SFTP_USERNAME:-sftp_user}
    ports:
      - "2222:22"
    environment:
      - SFTP_ROOT_FOLDER=/sftp/data
    volumes:
      - /Users/${USER}/projects/python/docling_server/content:/sftp/data
      - ./ssh_keys/authorized_keys:/tmp/authorized_keys:ro
